export default {
  uuid: '33e671bc-d17f-42b4-9aad-3f32260f4685',
  enabled: true,
  name: 'Mock Ecomm',
  storeUrl: 'https://mockecomm.test',
  trackingUrl: 'mockecomm.delivery.after.sale',
  email: 'ti@after.sale',
  confirmationType: 'email',
  channels: [{ id: 'sms', primary: true, data: {} }],
  handling: 20,
  picking: 10,
  integration: {
    platform: 'vtex',
    origin_domain: 'mockecomm.test',
    store_id: null,
    connectorUrl: 'https://mockecomm.test',
    connectorFields: {
      Url: 'https://mockecomm.test',
      'Any-Key': 'fake-key',
      'Any-Token': 'fake-token',
    },
  },
  features: ['feature'],
  logoUrl: 'https://send4.blob.core.windows.net/send4sprint/ecommerces/aftersale.png',
  createdAt: '2021-12-16T14:11:36.320Z',
  updatedAt: '2021-12-16T14:11:36.320Z',
  featureSettings: { loyalty: { enabled: true } },
  coupons: {
    selected: 'unique',
    rules: 'CONFIA',
    isActive: true,
    items: [
      {
        expirationDate: '2021-12-16T14:11:36.320Z',
        name: '10OFF',
        discount: null,
      },
    ],
  },
  utm: {},
  notifications: { custom: [], default: [12] },
  demo: true,
  couriers: [
    {
      id: 'correios',
      enabled: true,
      sacMail: 'email@email.com',
      customNames: ['correios'],
      courierUrl: null,
      connectorUrl: 'http://connector.url',
    },
  ],
  mappedEcommerceStatuses: {
    'payment-pending': 'payment-pending',
    'payment-approved': 'payment-approved',
    'window-to-cancel': 'payment-approved',
    handling: 'handling',
    'payment-denied': 'payment-denied',
    invoiced: 'invoiced',
    invoice: 'invoiced',
    canceled: 'canceled',
    cancel: 'canceled',
  },
  messages: {
    courier: [
      {
        id: 12,
        isCustomizable: true,
        title: 'Entrega finalizada com sucesso :)',
        detail: 'Eba! Entrega realizada!',
        customDetail: null,
        description: null,
        actionIds: [2, 6],
        tags: [],
      },
    ],
    platform: [
      {
        id: 1,
        isCustomizable: true,
        title: 'Pronto para envio.',
        detail:
          'Nota Fiscal emitida! Seu pedido já está pronto para envio! Mais novidades, em breve.',
        customDetail: null,
        description: null,
        actionIds: [],
        tags: [],
      },
    ],
    system: [
      {
        id: 13,
        isCustomizable: false,
        title: 'Entrega confirmada pelo cliente.',
        detail: null,
        customDetail: null,
        description: null,
        actionIds: [1, 6],
        tags: [],
      },
    ],
  },
};
